### ISSUE TITLE
Cowsay command needs an update

### ISSUE THREAD

**Issue by moxiegirl** [docker/tutorials#12]
@docker minor issue in the docs — docs.docker.com/mac/images/lin… last line should be — "CMD /usr/games/fortune -a | cowsay"

**Comment by thaJeztah** [comment]
PR was created here: https://github.com/docker/tutorials/pull/13

**Comment by thaJeztah** [comment]
#13 was merged, so this is fixed now (sorry, no permissions here, so can't close)

**Comment by moxiegirl** [comment]
@thaJeztah I'll close it.  I don't have perms to add you as a collaborator.  I'll see what I can do about that. :-D

**Comment by thaJeztah** [comment]
hehe, no prob. I'll just be generating more noise :wink:
