### ISSUE TITLE
Step 8 Needs to explicitly add login

### ISSUE THREAD

**Issue by moxiegirl** [docker/tutorials#20]
Docker has apparently stopped behaving as described in Step 8

docker push bonkydog/docker-whale

failed, and didn't walk me through logging in.

I had to run 

docker login

explicitly and then rerty

docker push bonkydog/docker-whale

to proceed.

**Comment by SvenDowideit** [comment]
yup, resolved in #18

**Comment by moxiegirl** [comment]
@SvenDowideit thanks
