### ISSUE TITLE
Bugs in /docs/linux/step_two.md 

### ISSUE THREAD

**Issue by authuir** [docker/tutorials#61]
fix the error that make the next page of https://github.com/docker/tutorials/blob/master/docs/linux/step_two.md 
to 
https://github.com/docker/tutorials/blob/master/docs/linux/step_three 
instead of 
https://github.com/docker/tutorials/blob/master/docs/linux/step_three.md

**Comment by aditirajagopal** [comment]
#dibs

**Comment by aditirajagopal** [comment]
#63 took care of this. This issue can be closed

**Comment by thaJeztah** [comment]
oh, yup! closing, thanks!
